spring:
  datasource:
    # 로컬 MySQL
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 1000  # 배치사이즈를 명시적으로 설정해줘야 적용됨!
    show-sql: false

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
#      host: localhost
#      port: 6379

# rabbitmq 설정
  rabbitmq:
    host: ${RABBITMQ_HOST} # RabbitMQ host ip
    port: 5672 # RabbitMQ port
    username: ${RABBITMQ_USERNAME} # RabbitMQ 웹 관리 콘솔 아이디
    password: ${RABBITMQ_PASSWORD} # RabbitMQ 웹 관리 콘솔 비밀번호
#    host: localhost # RabbitMQ host ip
#    port: 5672 # RabbitMQ port
#    username: guest # RabbitMQ 웹 관리 콘솔 아이디
#    password: guest # RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: test-queue # 사용할 queue 이름
  exchange:
    name: test-exchange # 사용할 exchange 이름
  routing:
    key: test-key
#  queue:
#    name: sample-queue # 사용할 queue 이름
#  exchange:
#    name: sample-exchange # 사용할 exchange 이름
#  routing:
#    key: key

management:
  endpoints:
    web:
      exposure:
        include: "*"